#
# Cookbook Name:: kyotocabinet
# Recipe:: default
#
# Copyright 2013, Go Travel Ltd.
#
# All rights reserved - Do Not Redistribute
#
if node['kyotocabinet']['user'] != 'root'
  bash "add_include_directive" do
    cwd "/home/#{node['kyotocabinet']['user']}"
    user node['go']['user']
    group node['go']['user']
    code <<-EOH
      cat << 'EOF' >> /home/#{node['kyotocabinet']['user']}/.bashrc
      # Generated by Chef add_include_directive]
      for i in #{node['kyotocabinet']['shell_d']}/*.sh; do
        if [ -r "$i" ]; then
          if [ "$PS1" ]; then
            . "$i"
          else
            . "$i" >/dev/null 2>&1
          fi
        fi
      done
    EOH
    not_if "grep 'Generated by Chef add_include_directive' /home/#{node['go']['user']}/.bashrc"
  end
end

bash "kyotocabinet_compile" do
  cwd node['kyotocabinet']['src']['tmpdir']
  user node['kyotocabinet']['user']
  group node['kyotocabinet']['user']
  code <<-EOH.gsub(/^\s+/, '')
    tar xzf "#{Chef::Config[:file_cache_path]}/kyotocabinet-#{node['kyotocabinet']['version']}.tar.gz"
    cd kyotocabinet-#{node['kyotocabinet']['version']}
    ./configure --prefix=#{node['kyotocabinet']['src']['prefix']} &&
    make && make install &&
    cd ~/ && rm -rf /tmp/kyotocabinet-#{node['kyotocabinet']['version']}
  EOH
  action :nothing
end

bash "kyotocabinet_set_variables" do
  cwd node['kyotocabinet']['shell_d']
  user node['kyotocabinet']['user']
  group node['kyotocabinet']['user']
  code <<-EOH.gsub(/^\s+/, '')
  cat << 'EOF' > kyotocabinet.sh
  # Generated by Chef [kyotocabinet]
  export LD_LIBRARY_PATH="#{node['kyotocabinet']['src']['prefix']}/lib"
  export PKG_CONFIG_PATH="#{node['kyotocabinet']['src']['prefix']}/lib/pkgconfig"
  EOF
  chmod 0755 kyotocabinet.sh
  EOH
  action :nothing
end

remote_file "#{Chef::Config[:file_cache_path]}/kyotocabinet-#{node['kyotocabinet']['version']}.tar.gz" do
  source "http://fallabs.com/kyotocabinet/pkg/kyotocabinet-#{node['kyotocabinet']['version']}.tar.gz"
  checksum node['kyotocabinet']['checksum']
  mode 0755
  action :create
  notifies :run, "bash[kyotocabinet_compile]", :immediately
  notifies :run, "bash[kyotocabinet_set_variables]", :immediately
  not_if "strings #{node['kyotocabinet']['src']['prefix']}/lib/libkyotocabinet.so|grep #{node['kyotocabinet']['version']}"
end
